### ISSUE TITLE
Confirm ffi compiler version?

### ISSUE THREAD

**Issue by crafterm** [cotag/http-parser#9]
Hi Team,

Hope all is going well.

Wanted to confirm the following change:

https://github.com/cotag/http-parser/blob/411825c2769b5894131ceebe910e0210cd047ea1/http-parser.gemspec#L21

It appears ffi-compiler is only available up to 1.0.1:

![image](https://user-images.githubusercontent.com/397/101309686-0d5cae80-38a1-11eb-9c61-35b39223de4f.png)

and its ffi itself that is 1.13.1:

![image](https://user-images.githubusercontent.com/397/101309728-27968c80-38a1-11eb-818f-9cc0fd020c82.png)

Building locally does indeed work but the resulting gem appears uninstallable?

```
➜  http-parser git:(master) gem install http-parser-1.2.2.gem
ERROR:  Could not find a valid gem 'ffi-compiler' (>= 1.13.1, < 2.0) (required by 'http-parser-1.2.2.gem' (>= 0)) in any repository
ERROR:  Possible alternatives: ffi-compiler
➜  http-parser git:(master)
```

Cheers,

Marcus

**Comment by bumi** [comment]
I am trying to use the latest master (which includes a fix for Apple M1) as dependency and I got the same issue.
I think that should be `1.0.1` ?
